on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 20.2.0
      - uses: actions/setup-java@v3.11.10
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@10.3
        with:
          tools-deps: '1.11.1.1208'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - run: clojure -M:dev -m br.dev.zz.mogno.dev
      - uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            target
